# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stanza.hub.v1 import stream_pb2 as stanza_dot_hub_dot_v1_dot_stream__pb2


class StreamBalancerServiceStub(object):
    """Experimental feature for fair prioritised balancing of streaming activities.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStreams = channel.unary_unary(
                '/stanza.hub.v1.StreamBalancerService/UpdateStreams',
                request_serializer=stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsRequest.SerializeToString,
                response_deserializer=stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsResponse.FromString,
                )


class StreamBalancerServiceServicer(object):
    """Experimental feature for fair prioritised balancing of streaming activities.
    """

    def UpdateStreams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamBalancerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateStreams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStreams,
                    request_deserializer=stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsRequest.FromString,
                    response_serializer=stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stanza.hub.v1.StreamBalancerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamBalancerService(object):
    """Experimental feature for fair prioritised balancing of streaming activities.
    """

    @staticmethod
    def UpdateStreams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stanza.hub.v1.StreamBalancerService/UpdateStreams',
            stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsRequest.SerializeToString,
            stanza_dot_hub_dot_v1_dot_stream__pb2.UpdateStreamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
