# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1GetBrowserContextResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"feature_configs": "list[V1FeatureConfig]"}

    attribute_map = {"feature_configs": "featureConfigs"}

    def __init__(self, feature_configs=None, _configuration=None):  # noqa: E501
        """V1GetBrowserContextResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._feature_configs = None
        self.discriminator = None

        if feature_configs is not None:
            self.feature_configs = feature_configs

    @property
    def feature_configs(self):
        """Gets the feature_configs of this V1GetBrowserContextResponse.  # noqa: E501


        :return: The feature_configs of this V1GetBrowserContextResponse.  # noqa: E501
        :rtype: list[V1FeatureConfig]
        """
        return self._feature_configs

    @feature_configs.setter
    def feature_configs(self, feature_configs):
        """Sets the feature_configs of this V1GetBrowserContextResponse.


        :param feature_configs: The feature_configs of this V1GetBrowserContextResponse.  # noqa: E501
        :type: list[V1FeatureConfig]
        """

        self._feature_configs = feature_configs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1GetBrowserContextResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GetBrowserContextResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1GetBrowserContextResponse):
            return True

        return self.to_dict() != other.to_dict()
