# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1GetServiceConfigResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "version": "str",
        "config_data_sent": "bool",
        "config": "V1ServiceConfig",
    }

    attribute_map = {
        "version": "version",
        "config_data_sent": "configDataSent",
        "config": "config",
    }

    def __init__(
        self, version=None, config_data_sent=None, config=None, _configuration=None
    ):  # noqa: E501
        """V1GetServiceConfigResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._version = None
        self._config_data_sent = None
        self._config = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if config_data_sent is not None:
            self.config_data_sent = config_data_sent
        if config is not None:
            self.config = config

    @property
    def version(self):
        """Gets the version of this V1GetServiceConfigResponse.  # noqa: E501


        :return: The version of this V1GetServiceConfigResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1GetServiceConfigResponse.


        :param version: The version of this V1GetServiceConfigResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def config_data_sent(self):
        """Gets the config_data_sent of this V1GetServiceConfigResponse.  # noqa: E501


        :return: The config_data_sent of this V1GetServiceConfigResponse.  # noqa: E501
        :rtype: bool
        """
        return self._config_data_sent

    @config_data_sent.setter
    def config_data_sent(self, config_data_sent):
        """Sets the config_data_sent of this V1GetServiceConfigResponse.


        :param config_data_sent: The config_data_sent of this V1GetServiceConfigResponse.  # noqa: E501
        :type: bool
        """

        self._config_data_sent = config_data_sent

    @property
    def config(self):
        """Gets the config of this V1GetServiceConfigResponse.  # noqa: E501


        :return: The config of this V1GetServiceConfigResponse.  # noqa: E501
        :rtype: V1ServiceConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this V1GetServiceConfigResponse.


        :param config: The config of this V1GetServiceConfigResponse.  # noqa: E501
        :type: V1ServiceConfig
        """

        self._config = config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1GetServiceConfigResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GetServiceConfigResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1GetServiceConfigResponse):
            return True

        return self.to_dict() != other.to_dict()
