# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1GetTokenResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "granted": "bool",
        "token": "str",
        "reason": "V1Reason",
        "mode": "V1Mode",
    }

    attribute_map = {
        "granted": "granted",
        "token": "token",
        "reason": "reason",
        "mode": "mode",
    }

    def __init__(
        self, granted=None, token=None, reason=None, mode=None, _configuration=None
    ):  # noqa: E501
        """V1GetTokenResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._granted = None
        self._token = None
        self._reason = None
        self._mode = None
        self.discriminator = None

        self.granted = granted
        if token is not None:
            self.token = token
        if reason is not None:
            self.reason = reason
        if mode is not None:
            self.mode = mode

    @property
    def granted(self):
        """Gets the granted of this V1GetTokenResponse.  # noqa: E501


        :return: The granted of this V1GetTokenResponse.  # noqa: E501
        :rtype: bool
        """
        return self._granted

    @granted.setter
    def granted(self, granted):
        """Sets the granted of this V1GetTokenResponse.


        :param granted: The granted of this V1GetTokenResponse.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and granted is None:
            raise ValueError(
                "Invalid value for `granted`, must not be `None`"
            )  # noqa: E501

        self._granted = granted

    @property
    def token(self):
        """Gets the token of this V1GetTokenResponse.  # noqa: E501


        :return: The token of this V1GetTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this V1GetTokenResponse.


        :param token: The token of this V1GetTokenResponse.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def reason(self):
        """Gets the reason of this V1GetTokenResponse.  # noqa: E501


        :return: The reason of this V1GetTokenResponse.  # noqa: E501
        :rtype: V1Reason
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this V1GetTokenResponse.


        :param reason: The reason of this V1GetTokenResponse.  # noqa: E501
        :type: V1Reason
        """

        self._reason = reason

    @property
    def mode(self):
        """Gets the mode of this V1GetTokenResponse.  # noqa: E501


        :return: The mode of this V1GetTokenResponse.  # noqa: E501
        :rtype: V1Mode
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this V1GetTokenResponse.


        :param mode: The mode of this V1GetTokenResponse.  # noqa: E501
        :type: V1Mode
        """

        self._mode = mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1GetTokenResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1GetTokenResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1GetTokenResponse):
            return True

        return self.to_dict() != other.to_dict()
