# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1HeaderTraceConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "span_selectors": "list[V1SpanSelector]",
        "request_header_names": "list[str]",
        "response_header_names": "list[str]",
    }

    attribute_map = {
        "span_selectors": "spanSelectors",
        "request_header_names": "requestHeaderNames",
        "response_header_names": "responseHeaderNames",
    }

    def __init__(
        self,
        span_selectors=None,
        request_header_names=None,
        response_header_names=None,
        _configuration=None,
    ):  # noqa: E501
        """V1HeaderTraceConfig - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._span_selectors = None
        self._request_header_names = None
        self._response_header_names = None
        self.discriminator = None

        if span_selectors is not None:
            self.span_selectors = span_selectors
        if request_header_names is not None:
            self.request_header_names = request_header_names
        if response_header_names is not None:
            self.response_header_names = response_header_names

    @property
    def span_selectors(self):
        """Gets the span_selectors of this V1HeaderTraceConfig.  # noqa: E501


        :return: The span_selectors of this V1HeaderTraceConfig.  # noqa: E501
        :rtype: list[V1SpanSelector]
        """
        return self._span_selectors

    @span_selectors.setter
    def span_selectors(self, span_selectors):
        """Sets the span_selectors of this V1HeaderTraceConfig.


        :param span_selectors: The span_selectors of this V1HeaderTraceConfig.  # noqa: E501
        :type: list[V1SpanSelector]
        """

        self._span_selectors = span_selectors

    @property
    def request_header_names(self):
        """Gets the request_header_names of this V1HeaderTraceConfig.  # noqa: E501


        :return: The request_header_names of this V1HeaderTraceConfig.  # noqa: E501
        :rtype: list[str]
        """
        return self._request_header_names

    @request_header_names.setter
    def request_header_names(self, request_header_names):
        """Sets the request_header_names of this V1HeaderTraceConfig.


        :param request_header_names: The request_header_names of this V1HeaderTraceConfig.  # noqa: E501
        :type: list[str]
        """

        self._request_header_names = request_header_names

    @property
    def response_header_names(self):
        """Gets the response_header_names of this V1HeaderTraceConfig.  # noqa: E501


        :return: The response_header_names of this V1HeaderTraceConfig.  # noqa: E501
        :rtype: list[str]
        """
        return self._response_header_names

    @response_header_names.setter
    def response_header_names(self, response_header_names):
        """Sets the response_header_names of this V1HeaderTraceConfig.


        :param response_header_names: The response_header_names of this V1HeaderTraceConfig.  # noqa: E501
        :type: list[str]
        """

        self._response_header_names = response_header_names

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1HeaderTraceConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1HeaderTraceConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1HeaderTraceConfig):
            return True

        return self.to_dict() != other.to_dict()
