# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1QueryGuardHealthRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"selector": "V1GuardFeatureSelector", "priority_boost": "int"}

    attribute_map = {"selector": "selector", "priority_boost": "priorityBoost"}

    def __init__(
        self, selector=None, priority_boost=None, _configuration=None
    ):  # noqa: E501
        """V1QueryGuardHealthRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._selector = None
        self._priority_boost = None
        self.discriminator = None

        if selector is not None:
            self.selector = selector
        if priority_boost is not None:
            self.priority_boost = priority_boost

    @property
    def selector(self):
        """Gets the selector of this V1QueryGuardHealthRequest.  # noqa: E501

        Only tags which are used for quota management should be included here - i.e. the list of quota_tags returned by the GetGuardConfig endpoint for this Guard. If tags are in use only one quota token will be issued at a time.  Required: GuardName, featureName, environment  # noqa: E501

        :return: The selector of this V1QueryGuardHealthRequest.  # noqa: E501
        :rtype: V1GuardFeatureSelector
        """
        return self._selector

    @selector.setter
    def selector(self, selector):
        """Sets the selector of this V1QueryGuardHealthRequest.

        Only tags which are used for quota management should be included here - i.e. the list of quota_tags returned by the GetGuardConfig endpoint for this Guard. If tags are in use only one quota token will be issued at a time.  Required: GuardName, featureName, environment  # noqa: E501

        :param selector: The selector of this V1QueryGuardHealthRequest.  # noqa: E501
        :type: V1GuardFeatureSelector
        """

        self._selector = selector

    @property
    def priority_boost(self):
        """Gets the priority_boost of this V1QueryGuardHealthRequest.  # noqa: E501

        Used to boost priority - SDK can increase or decrease priority of request, relative to normal feature priority. For instance, a customer may wish to boost the priority of paid user traffic over free tier. Priority boosts may also be negative - for example, one might deprioritise bot traffic.  # noqa: E501

        :return: The priority_boost of this V1QueryGuardHealthRequest.  # noqa: E501
        :rtype: int
        """
        return self._priority_boost

    @priority_boost.setter
    def priority_boost(self, priority_boost):
        """Sets the priority_boost of this V1QueryGuardHealthRequest.

        Used to boost priority - SDK can increase or decrease priority of request, relative to normal feature priority. For instance, a customer may wish to boost the priority of paid user traffic over free tier. Priority boosts may also be negative - for example, one might deprioritise bot traffic.  # noqa: E501

        :param priority_boost: The priority_boost of this V1QueryGuardHealthRequest.  # noqa: E501
        :type: int
        """

        self._priority_boost = priority_boost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1QueryGuardHealthRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1QueryGuardHealthRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1QueryGuardHealthRequest):
            return True

        return self.to_dict() != other.to_dict()
