# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1StreamRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "feature": "str",
        "tags": "list[Hubv1Tag]",
        "priority_boost": "int",
        "stream_id": "str",
        "max_weight": "float",
        "min_weight": "float",
    }

    attribute_map = {
        "feature": "feature",
        "tags": "tags",
        "priority_boost": "priorityBoost",
        "stream_id": "streamId",
        "max_weight": "maxWeight",
        "min_weight": "minWeight",
    }

    def __init__(
        self,
        feature=None,
        tags=None,
        priority_boost=None,
        stream_id=None,
        max_weight=None,
        min_weight=None,
        _configuration=None,
    ):  # noqa: E501
        """V1StreamRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._feature = None
        self._tags = None
        self._priority_boost = None
        self._stream_id = None
        self._max_weight = None
        self._min_weight = None
        self.discriminator = None

        if feature is not None:
            self.feature = feature
        if tags is not None:
            self.tags = tags
        if priority_boost is not None:
            self.priority_boost = priority_boost
        self.stream_id = stream_id
        self.max_weight = max_weight
        self.min_weight = min_weight

    @property
    def feature(self):
        """Gets the feature of this V1StreamRequest.  # noqa: E501


        :return: The feature of this V1StreamRequest.  # noqa: E501
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """Sets the feature of this V1StreamRequest.


        :param feature: The feature of this V1StreamRequest.  # noqa: E501
        :type: str
        """

        self._feature = feature

    @property
    def tags(self):
        """Gets the tags of this V1StreamRequest.  # noqa: E501


        :return: The tags of this V1StreamRequest.  # noqa: E501
        :rtype: list[Hubv1Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this V1StreamRequest.


        :param tags: The tags of this V1StreamRequest.  # noqa: E501
        :type: list[Hubv1Tag]
        """

        self._tags = tags

    @property
    def priority_boost(self):
        """Gets the priority_boost of this V1StreamRequest.  # noqa: E501

        optional - allows priority to be increased or reduced relative to normal default or feature priority.  # noqa: E501

        :return: The priority_boost of this V1StreamRequest.  # noqa: E501
        :rtype: int
        """
        return self._priority_boost

    @priority_boost.setter
    def priority_boost(self, priority_boost):
        """Sets the priority_boost of this V1StreamRequest.

        optional - allows priority to be increased or reduced relative to normal default or feature priority.  # noqa: E501

        :param priority_boost: The priority_boost of this V1StreamRequest.  # noqa: E501
        :type: int
        """

        self._priority_boost = priority_boost

    @property
    def stream_id(self):
        """Gets the stream_id of this V1StreamRequest.  # noqa: E501

        Unique identifier for this stream - may be meaningful or a UUID. Assigned by requestor.  # noqa: E501

        :return: The stream_id of this V1StreamRequest.  # noqa: E501
        :rtype: str
        """
        return self._stream_id

    @stream_id.setter
    def stream_id(self, stream_id):
        """Sets the stream_id of this V1StreamRequest.

        Unique identifier for this stream - may be meaningful or a UUID. Assigned by requestor.  # noqa: E501

        :param stream_id: The stream_id of this V1StreamRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and stream_id is None:
            raise ValueError(
                "Invalid value for `stream_id`, must not be `None`"
            )  # noqa: E501

        self._stream_id = stream_id

    @property
    def max_weight(self):
        """Gets the max_weight of this V1StreamRequest.  # noqa: E501


        :return: The max_weight of this V1StreamRequest.  # noqa: E501
        :rtype: float
        """
        return self._max_weight

    @max_weight.setter
    def max_weight(self, max_weight):
        """Sets the max_weight of this V1StreamRequest.


        :param max_weight: The max_weight of this V1StreamRequest.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and max_weight is None:
            raise ValueError(
                "Invalid value for `max_weight`, must not be `None`"
            )  # noqa: E501

        self._max_weight = max_weight

    @property
    def min_weight(self):
        """Gets the min_weight of this V1StreamRequest.  # noqa: E501

        Minimum weight that may be allocated to this stream. If this weight cannot be allocated then the stream cannot be served.  # noqa: E501

        :return: The min_weight of this V1StreamRequest.  # noqa: E501
        :rtype: float
        """
        return self._min_weight

    @min_weight.setter
    def min_weight(self, min_weight):
        """Sets the min_weight of this V1StreamRequest.

        Minimum weight that may be allocated to this stream. If this weight cannot be allocated then the stream cannot be served.  # noqa: E501

        :param min_weight: The min_weight of this V1StreamRequest.  # noqa: E501
        :type: float
        """
        if self._configuration.client_side_validation and min_weight is None:
            raise ValueError(
                "Invalid value for `min_weight`, must not be `None`"
            )  # noqa: E501

        self._min_weight = min_weight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1StreamRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1StreamRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1StreamRequest):
            return True

        return self.to_dict() != other.to_dict()
