# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1TokenLease(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "duration_msec": "int",
        "token": "str",
        "feature": "str",
        "priority_boost": "int",
        "weight": "float",
        "reason": "V1Reason",
        "expires_at": "datetime",
        "mode": "V1Mode",
    }

    attribute_map = {
        "duration_msec": "durationMsec",
        "token": "token",
        "feature": "feature",
        "priority_boost": "priorityBoost",
        "weight": "weight",
        "reason": "reason",
        "expires_at": "expiresAt",
        "mode": "mode",
    }

    def __init__(
        self,
        duration_msec=None,
        token=None,
        feature=None,
        priority_boost=None,
        weight=None,
        reason=None,
        expires_at=None,
        mode=None,
        _configuration=None,
    ):  # noqa: E501
        """V1TokenLease - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._duration_msec = None
        self._token = None
        self._feature = None
        self._priority_boost = None
        self._weight = None
        self._reason = None
        self._expires_at = None
        self._mode = None
        self.discriminator = None

        if duration_msec is not None:
            self.duration_msec = duration_msec
        if token is not None:
            self.token = token
        if feature is not None:
            self.feature = feature
        if priority_boost is not None:
            self.priority_boost = priority_boost
        if weight is not None:
            self.weight = weight
        if reason is not None:
            self.reason = reason
        if expires_at is not None:
            self.expires_at = expires_at
        if mode is not None:
            self.mode = mode

    @property
    def duration_msec(self):
        """Gets the duration_msec of this V1TokenLease.  # noqa: E501


        :return: The duration_msec of this V1TokenLease.  # noqa: E501
        :rtype: int
        """
        return self._duration_msec

    @duration_msec.setter
    def duration_msec(self, duration_msec):
        """Sets the duration_msec of this V1TokenLease.


        :param duration_msec: The duration_msec of this V1TokenLease.  # noqa: E501
        :type: int
        """

        self._duration_msec = duration_msec

    @property
    def token(self):
        """Gets the token of this V1TokenLease.  # noqa: E501


        :return: The token of this V1TokenLease.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this V1TokenLease.


        :param token: The token of this V1TokenLease.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def feature(self):
        """Gets the feature of this V1TokenLease.  # noqa: E501


        :return: The feature of this V1TokenLease.  # noqa: E501
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature):
        """Sets the feature of this V1TokenLease.


        :param feature: The feature of this V1TokenLease.  # noqa: E501
        :type: str
        """

        self._feature = feature

    @property
    def priority_boost(self):
        """Gets the priority_boost of this V1TokenLease.  # noqa: E501


        :return: The priority_boost of this V1TokenLease.  # noqa: E501
        :rtype: int
        """
        return self._priority_boost

    @priority_boost.setter
    def priority_boost(self, priority_boost):
        """Sets the priority_boost of this V1TokenLease.


        :param priority_boost: The priority_boost of this V1TokenLease.  # noqa: E501
        :type: int
        """

        self._priority_boost = priority_boost

    @property
    def weight(self):
        """Gets the weight of this V1TokenLease.  # noqa: E501


        :return: The weight of this V1TokenLease.  # noqa: E501
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this V1TokenLease.


        :param weight: The weight of this V1TokenLease.  # noqa: E501
        :type: float
        """

        self._weight = weight

    @property
    def reason(self):
        """Gets the reason of this V1TokenLease.  # noqa: E501


        :return: The reason of this V1TokenLease.  # noqa: E501
        :rtype: V1Reason
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this V1TokenLease.


        :param reason: The reason of this V1TokenLease.  # noqa: E501
        :type: V1Reason
        """

        self._reason = reason

    @property
    def expires_at(self):
        """Gets the expires_at of this V1TokenLease.  # noqa: E501


        :return: The expires_at of this V1TokenLease.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this V1TokenLease.


        :param expires_at: The expires_at of this V1TokenLease.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    @property
    def mode(self):
        """Gets the mode of this V1TokenLease.  # noqa: E501


        :return: The mode of this V1TokenLease.  # noqa: E501
        :rtype: V1Mode
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this V1TokenLease.


        :param mode: The mode of this V1TokenLease.  # noqa: E501
        :type: V1Mode
        """

        self._mode = mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1TokenLease, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1TokenLease):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1TokenLease):
            return True

        return self.to_dict() != other.to_dict()
