# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1UpdateStreamsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "guard_name": "str",
        "environment": "str",
        "requests": "list[V1StreamRequest]",
        "ended": "list[str]",
    }

    attribute_map = {
        "guard_name": "guardName",
        "environment": "environment",
        "requests": "requests",
        "ended": "ended",
    }

    def __init__(
        self,
        guard_name=None,
        environment=None,
        requests=None,
        ended=None,
        _configuration=None,
    ):  # noqa: E501
        """V1UpdateStreamsRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._guard_name = None
        self._environment = None
        self._requests = None
        self._ended = None
        self.discriminator = None

        self.guard_name = guard_name
        self.environment = environment
        if requests is not None:
            self.requests = requests
        if ended is not None:
            self.ended = ended

    @property
    def guard_name(self):
        """Gets the guard_name of this V1UpdateStreamsRequest.  # noqa: E501


        :return: The guard_name of this V1UpdateStreamsRequest.  # noqa: E501
        :rtype: str
        """
        return self._guard_name

    @guard_name.setter
    def guard_name(self, guard_name):
        """Sets the guard_name of this V1UpdateStreamsRequest.


        :param guard_name: The guard_name of this V1UpdateStreamsRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and guard_name is None:
            raise ValueError(
                "Invalid value for `guard_name`, must not be `None`"
            )  # noqa: E501

        self._guard_name = guard_name

    @property
    def environment(self):
        """Gets the environment of this V1UpdateStreamsRequest.  # noqa: E501


        :return: The environment of this V1UpdateStreamsRequest.  # noqa: E501
        :rtype: str
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """Sets the environment of this V1UpdateStreamsRequest.


        :param environment: The environment of this V1UpdateStreamsRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and environment is None:
            raise ValueError(
                "Invalid value for `environment`, must not be `None`"
            )  # noqa: E501

        self._environment = environment

    @property
    def requests(self):
        """Gets the requests of this V1UpdateStreamsRequest.  # noqa: E501


        :return: The requests of this V1UpdateStreamsRequest.  # noqa: E501
        :rtype: list[V1StreamRequest]
        """
        return self._requests

    @requests.setter
    def requests(self, requests):
        """Sets the requests of this V1UpdateStreamsRequest.


        :param requests: The requests of this V1UpdateStreamsRequest.  # noqa: E501
        :type: list[V1StreamRequest]
        """

        self._requests = requests

    @property
    def ended(self):
        """Gets the ended of this V1UpdateStreamsRequest.  # noqa: E501


        :return: The ended of this V1UpdateStreamsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._ended

    @ended.setter
    def ended(self, ended):
        """Sets the ended of this V1UpdateStreamsRequest.


        :param ended: The ended of this V1UpdateStreamsRequest.  # noqa: E501
        :type: list[str]
        """

        self._ended = ended

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1UpdateStreamsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1UpdateStreamsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1UpdateStreamsRequest):
            return True

        return self.to_dict() != other.to_dict()
