# coding: utf-8

"""
    Stanza Hub API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@stanza.systems
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six
from getstanza.hub.configuration import Configuration


class V1ValidateTokenResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"valid": "bool", "tokens_valid": "list[V1TokenValid]"}

    attribute_map = {"valid": "valid", "tokens_valid": "tokensValid"}

    def __init__(
        self, valid=None, tokens_valid=None, _configuration=None
    ):  # noqa: E501
        """V1ValidateTokenResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._valid = None
        self._tokens_valid = None
        self.discriminator = None

        if valid is not None:
            self.valid = valid
        if tokens_valid is not None:
            self.tokens_valid = tokens_valid

    @property
    def valid(self):
        """Gets the valid of this V1ValidateTokenResponse.  # noqa: E501


        :return: The valid of this V1ValidateTokenResponse.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this V1ValidateTokenResponse.


        :param valid: The valid of this V1ValidateTokenResponse.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    @property
    def tokens_valid(self):
        """Gets the tokens_valid of this V1ValidateTokenResponse.  # noqa: E501


        :return: The tokens_valid of this V1ValidateTokenResponse.  # noqa: E501
        :rtype: list[V1TokenValid]
        """
        return self._tokens_valid

    @tokens_valid.setter
    def tokens_valid(self, tokens_valid):
        """Sets the tokens_valid of this V1ValidateTokenResponse.


        :param tokens_valid: The tokens_valid of this V1ValidateTokenResponse.  # noqa: E501
        :type: list[V1TokenValid]
        """

        self._tokens_valid = tokens_valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1ValidateTokenResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ValidateTokenResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1ValidateTokenResponse):
            return True

        return self.to_dict() != other.to_dict()
