[tool.poetry]
name = "sqs"
version = "0.1.0"
description = ""
authors = ["Jamie Kuppens <jamie@sre.is>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.34.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
