[tool.poetry]
name = "getstanza"
version = "0.0.1-beta1"
description = "Python SDK for adding Stanza Systems fault tolerance to your python 3 service."
authors = ["Stanza Systems <hello@sre.is>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
opentelemetry-api = "^1.20.0"
opentelemetry-sdk = "^1.20.0"
opentelemetry-exporter-otlp-proto-grpc = "^1.20.0"
six = "^1.16.0"
python-dateutil = "^2.8.2"
aiohttp = "^3.8.6"
urllib3 = "^2.1.0"
stanza-apis-grpc-python = "^1.60.0.1.20231026123415+1a9dca8fa2f6"
stanza-apis-protocolbuffers-python = "^25.1.0.1.20231026123415+1a9dca8fa2f6"
protoc-gen-openapiv2 = "^0.0.1"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "buf"
url = "https://buf.build/gen/python"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
