[tool.poetry]
name = "getstanza"
version = "0.0.1-beta1"
description = "Python SDK for adding Stanza Systems fault tolerance to your python 3 service."
authors = ["Stanza Systems <hello@sre.is>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
opentelemetry-api = "^1.20.0"
opentelemetry-sdk = "^1.20.0"
opentelemetry-exporter-otlp-proto-grpc = "^1.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
