[tool.poetry]
name = "getstanza"
version = "0.0.1-beta1"
description = "Python SDK for adding Stanza Systems fault tolerance to your python 3 service."
authors = ["Stanza Systems <hello@sre.is>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
opentelemetry-api = "^1.20.0"
opentelemetry-sdk = "^1.20.0"
opentelemetry-exporter-otlp-proto-grpc = "^1.20.0"
six = "^1.16.0"
python-dateutil = "^2.8.2"
aiohttp = "^3.8.6"
urllib3 = "^2.1.0"
stanza-apis-grpc-python = "^1.60.0.1.20231026123415+1a9dca8fa2f6"
stanza-apis-protocolbuffers-python = "^25.1.0.1.20231026123415+1a9dca8fa2f6"
protoc-gen-openapiv2 = "^0.0.1"
stanza-apis-protocolbuffers-pyi = "^25.1.0.1.20231026123415+1a9dca8fa2f6"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "buf"
url = "https://buf.build/gen/python"
priority = "supplemental"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.23.2"
# We import a version of 'pytest-socket' with an additional fix that is
# unmerged as of now to prevent this plugin from breaking the VSCode debugger.
# We should switch back to a tag once this gets merged.
pytest-socket = { git = "https://github.com/magnasilvar/pytest-socket.git", rev = "403f31751822c79c525c6005fd1e96a366873969" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
